### ISSUE TITLE
mds_license.enterprise_license needs to be ignored from being replicated

### ISSUE THREAD

**Issue by psrpardhasaradhi** [Appdynamics/HA-toolkit#101]
In replicate.sh we need to add:
`replicate_ignore_table=mds_license.enterprise_license`

enterprise_license table in MDS schema is local to the controller server. We should not replicate it.

Else appserver does not start till we truncate this table.

`com.appdynamics.platform.services.license.LicenseValidationException: The license is not valid for this machine. The MAC address specified in the license is XXXX while system has these MAC addresses: [YYYY]`

**Comment by psrpardhasaradhi** [comment]
Fixed in 3.47

**Comment by cmayer68** [comment]
what a horrible architecture.

On Mon, Apr 1, 2019 at 11:11 AM Saradhi Potharaju <notifications@github.com>
wrote:

> Fixed in 3.47
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_Appdynamics_HA-2Dtoolkit_issues_101-23issuecomment-2D478685688&d=DwMCaQ&c=3_5eq9zYXWRS8ywqccmjfTRKM8mRLoQp6HBg1Tdb_Pc&r=nsJ1Vt4kkj1MF7fPuYx_OHpUcucCi7WPVJJQ5IIS6oA&m=ZVzgxzcIPQ7tEmL9kHDYR9il03Y6uDyt-5PCUfLyaig&s=2bLvn1UogskZf3mJ_X7NTMq3pSHe9O-9RlMfHrL9ad0&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_APNeTAZZxgYjWQ2xX8cIGEugPojpLBB2ks5vckvAgaJpZM4cDBop&d=DwMCaQ&c=3_5eq9zYXWRS8ywqccmjfTRKM8mRLoQp6HBg1Tdb_Pc&r=nsJ1Vt4kkj1MF7fPuYx_OHpUcucCi7WPVJJQ5IIS6oA&m=ZVzgxzcIPQ7tEmL9kHDYR9il03Y6uDyt-5PCUfLyaig&s=V1FcZlssNiVftQ81mW6Q-7V6MyKCdrNjsrU3uYuVI4Q&e=>
> .
>


-- 
*Curt Mayer* | Senior Architect, Customer Success
Office 707.540.3441 | Mobile 707.540.3441
<http://appdynamics.com/>
Watch  <http://appdynamics.wistia.com/medias/56gnkuk6mv>our Video | Try
<https://portal.appdynamics.com/account/signup/signupForm>our FREE Trial |
Twitter  <http://www.twitter.com/appdynamics>| Facebook
<http://www.facebook.com/pages/AppDynamics/193264136815?ref=nf>|
appdynamics.com <http://www.appdynamics.com/>
