### ISSUE TITLE
Sloppy "rm" behavior in replicate.sh : fix for cleanliness

### ISSUE THREAD

**Issue by scosol** [Appdynamics/HA-toolkit#108]
“$datadir/*log*” -> matches mds_topology and tries to delete it

Suggest: targeted "relay-log*." etc kinds of wildcards.

Context: line 1207:

	message "inhibit running of secondary and delete mysql/innodb logfiles"
	$SSH $secondary rm -f $APPD_ROOT/bin/controller.sh \
		"$innodb_logdir/ib_logfile*" \
		"$datadir/*log*" \
		$datadir/ibdata1 2>&1 | logonly

**Comment by cm68** [comment]
fixed in 3.62
