### ISSUE TITLE
save_mysql_passwd.sh fails

### ISSUE THREAD

**Issue by psrpardhasaradhi** [Appdynamics/HA-toolkit#16]
save_mysql_passwd.sh fails with error:

bash -x save_mysql_passwd.sh

**chown /opt/AppDynamics/Controller/db/.rootpw.obf
chown: missing operand after ‘/opt/AppDynamics/Controller/db/.rootpw.obf’**

Try 'chown --help' for more information.

This is because in HA/lib/ha.sh, RUNUSER is not defined but used.

**chown $RUNUSER $rootpw_obf**

**Comment by cmayer68** [comment]
fixed in 3.4
