### ISSUE TITLE
machine agent on secondary does not report till at least one failover happens

### ISSUE THREAD

**Issue by psrpardhasaradhi** [Appdynamics/HA-toolkit#32]
While setting up HA initially, the machine agent on secondary controller does not report yet because the appagent did not report at least once yet and hence the node is not created and machine agent is not tied to any application.

We might have to document this or we might have to pass application name initially for the first run of machine agent on secondary and once the appagent has reported at least once, we can fall back to not specify application name for machine agent.

**Comment by cmayer68** [comment]
fixed in 3.10.
