### ISSUE TITLE
DBOPLIMIT specified twice in watchdog.settings.template

### ISSUE THREAD

**Issue by psrpardhasaradhi** [Appdynamics/HA-toolkit#35]
For disabling this test for non SAN systems, I believe we increased the time. In the template file this is still specified twice and could cause confusion to customers. 

It would help if it is specified only once and comments are added to show that this test tries to create table and also asking them to set this to a fair value like 5 minutes for SAN systems

# The primary database cannot create a table: 5 Minutes
DBOPLIMIT=300
# disable this test for now, until we get more confidence in it
DBOPLIMIT=2000000000

**Comment by cmayer68** [comment]
an appropriate comment is added to the watchdog.settings.template for 3.7
