### ISSUE TITLE
multiple paths need to be checked for "pbrun"

### ISSUE THREAD

**Issue by psrpardhasaradhi** [Appdynamics/HA-toolkit#41]
Currently we pick pbrun from following path but this could also be in /usr/bin/pbrun (#78410).
We need to check PATH and if not in PATH, then other possible folders where pbrun is usually installed.

appdynamics-pbrun.sh

PBRUN=/usr/local/bin/pbrun

**Comment by cmayer68** [comment]
fixed in 3.7, in a slightly different way.  I only check /usr/local/bin and /usr/bin
