### ISSUE TITLE
appdynamics-machine-agent does not echo the status when used as standalone

### ISSUE THREAD

**Issue by psrpardhasaradhi** [Appdynamics/HA-toolkit#42]
Controller is not HA enabled but customer uses HA scripts to manage controller and machine agent services. The appdynamics-machine-agent does not echo the status of machine agent. Instead appdcontroller status needs to be issued everytime after start or stop to check the status.

It would be helpful to echo to stdout the result of start/stop/status commands when  appdynamics-machine-agent is used to manage machine agent if customer is not using appdcontroller.sh

**Comment by cmayer68** [comment]
fixed in 3.7
