### ISSUE TITLE
Seemingly benign error on basename command

### ISSUE THREAD

**Issue by ajsawyers22** [Appdynamics/HA-toolkit#48]
Running the scripts thru appdservice-noroot.sh (ver4.3) throws the following in addition to the expected output:

basename: missing operand
Try `basename --help' for more information.

After some trial and error it looks like the issue is with:

NAME=$(basename $(readlink -e $0))

**Comment by cmayer68** [comment]
will try to reproduce.

**Comment by cmayer68** [comment]
this is an artifact of using a different readlink, which does not support the -e option.
this is fixed by using a fixed path for everything, which won't pick up the wrong readlink.

fixed in 3.12
