### ISSUE TITLE
Syntax error after fresh install

### ISSUE THREAD

**Issue by ajsawyers22** [Appdynamics/HA-toolkit#52]
Running into this issue in 3.12, both zip and shar versions:

PWD:/apps/appdynamics/controller/HA $./appdservice-noroot.sh appdcontroller status
./appdservice-noroot.sh: line 101: syntax error near unexpected token `;;'
./appdservice-noroot.sh: line 101: `    ;;'

**Comment by cmayer68** [comment]
fixed in 3.14
