### ISSUE TITLE
controller_repl user has super privileges

### ISSUE THREAD

**Issue by psrpardhasaradhi** [Appdynamics/HA-toolkit#53]
HA toolkit grants all privileges on the controller_repl user for all objects. Although we could restrict the permissions to primary/secondary hosts (not using -W wildcard option) , there are cases where we receive requests that this is a vulnerability as a non-root user has all privileges.

For example, with FILE privilege user can write or read a file anywhere in the file system with the privileges of the mysqld daemon. 

As this user is for slave to connect to master, could we trim down the privileges?
https://dev.mysql.com/doc/refman/5.5/en/replication-howto-repuser.html

**Comment by cmayer68** [comment]
fixed in 3.14

**Comment by psrpardhasaradhi** [comment]
Hi Curt,

We might need a small change.

-W we ask to use if wildcard has to be used in the grant. But wildcard is false by default and if -W is passed then it is set to true. But in evaluation if wildcard is true we are setting cannonical hostname in grant.

So if -W is specified we are using cannonical hostname and if not specified we are using wildcard which goes against the usage message.

Saradhi

**Comment by cmayer68** [comment]
really fixed in 3.14.1
