### ISSUE TITLE
-W wildcard option does not work

### ISSUE THREAD

**Issue by psrpardhasaradhi** [Appdynamics/HA-toolkit#54]
In replicate.sh, we initialize wildcard=false. So it is expected that the permissions are granted for specific hosts instead of wildcard % if -W option is not specified. This does not work because we check the condition:

if [ -z $wildcard ] ; then

But as the wildcard string is never null as we initialise it to false, this condition is not met.

I tested by not initialising wildcard=false (have set wildcard=) and then the condition is evaluated and privileges are granted on specific hosts.

**Comment by cmayer68** [comment]
fixed in 3.14
