### ISSUE TITLE
Use `sync_binlog=1` to prevent replication breaks when active mysqld crashes

### ISSUE THREAD

**Issue by mprzybylski** [Appdynamics/HA-toolkit#58]
Just finished a customer call where replication broke after the active controller crashed and restarted.

Restored replication by skipping slave ahead to the next binlog file.

This can probably be prevented with `sync_binlog=1` in MySQL.

# Performance and Documentation Impacts:
* Adds a synchronous write, (`fsync()`) to the critical path of each transaction commit
  * This could impact metric ingest rate for very large controller installations
  * `bin-log.*` should be written to PCIe or NVMe SSDs to minimize performance impact
* Any documentation we have on sizing SSDs for MySQL redo logs should be updated to accommodate bin-logs as well.

# References:
* https://www.percona.com/blog/2014/10/08/mysql-replication-got-fatal-error-1236-causes-and-cures/ (See `Client requested master to start replication from impossible position;`)

**Comment by cmayer68** [comment]
fixed in 3.17
