### ISSUE TITLE
Need a switch to not update appdynamics.controller.hostName if user does not want to do so

### ISSUE THREAD

**Issue by psrpardhasaradhi** [Appdynamics/HA-toolkit#59]
Currently if internal VIP is not specified then we parse external VIP and update following properties. We have few customers who do not have internal VIP and external VIP is not resolvable from controller host. So they set these properties manually to the actual host name and port manually but replicate script overrides it. So we should provide a switch where these details are not overridden in cases like this.

-Dappdynamics.controller.hostName
-Dappdynamics.controller.port
-Dappdynamics.controller.services.hostName
-Dappdynamics.controller.services.port

A workaround I see is to pass the internal vip as http://localhost:port so that irrespective of which server is primary this works.

**Comment by rnav1234** [comment]
Hi Saradhi,
Can you please elaborate a little more on the use case you are describing. 
Are you really saying that -i that should identify internal VIP name does not exist? 
What is the problem with specifying -i http://localhost:<port> ?
Cheers,
R

**Comment by psrpardhasaradhi** [comment]
Customer agreed to use localhost everytime they run replicate. Closing this issue.
