### ISSUE TITLE
Need ability to set Tier name and node name for internal monitoring.

### ISSUE THREAD

**Issue by psrpardhasaradhi** [Appdynamics/HA-toolkit#60]
In setmonitor.sh, monitoring tier is hard coded. Using -m option, we need to allow customers to specify tier and node name as well as there have been requests for this.

monitor_tier="App Server"

**Comment by cmayer68** [comment]
new function in 3.18, adds tier_name to setmonitor.sh -m argument.

**Comment by cmayer68** [comment]
node name as host name will be very hard to fix, and I'm not sure about the use case.
tier I can see, and it's already in.

**Comment by psrpardhasaradhi** [comment]
node-name is currently set to short name of the host by setmonitor.sh. There was a request asking for ability to customize tier and node names but we having short hostname itself as nodename would help identify nodes. So current change is sufficient for this. Closing the request.
