### ISSUE TITLE
Sanity check for /etc/hosts does not consider same hostname alias in different domain

### ISSUE THREAD

**Issue by psrpardhasaradhi** [Appdynamics/HA-toolkit#77]
1) Consider primary to be myserver.domainA and secondary to be myserver.domainB. Hostname is same but domain name is different.

2) If we run replicate without wanting to use wildcard grants (which is the default), the replicate fails with error:

The HA servers share a common hostname or alias 'myserver'. Please fix this and re-run.

3) We need to bypass this check if they have same hostname but in different domain

4) We may also have to move this check ahead of stopping the primary controller as it is already stopped by the time this check is encountered.

This is introduced in 3.27.4

@rnav1234

**Comment by rnav1234** [comment]
Thank you Saradhi. Nice catch.  I believe this is patched in 3.28.5
