### ISSUE TITLE
appdcontroller init script should also delete osgi-cache and domain1/generated

### ISSUE THREAD

**Issue by mprzybylski** [Appdynamics/HA-toolkit#90]
When starting the controller app server, Enterprise Console preemptively deletes `<Controller Home>/appserver/glassfish/domains/domain1/generated` and `<Controller Home>/appserver/glassfish/domains/domain1/osgi-cache` before starting glassfish.

The `appdcontroller` init script should also delete those files before invoking `controller.sh start-appserver`

**Comment by psrpardhasaradhi** [comment]
Fixed in 3.47

**Comment by cmayer68** [comment]
good show.

On Mon, Apr 1, 2019 at 11:11 AM Saradhi Potharaju <notifications@github.com>
wrote:

> Fixed in 3.47
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_Appdynamics_HA-2Dtoolkit_issues_90-23issuecomment-2D478685767&d=DwMCaQ&c=3_5eq9zYXWRS8ywqccmjfTRKM8mRLoQp6HBg1Tdb_Pc&r=nsJ1Vt4kkj1MF7fPuYx_OHpUcucCi7WPVJJQ5IIS6oA&m=C1-GFK88oKyYhu9ikTbOj7aLgY91vwhHUZO9-h-k_0g&s=UBWtXjw7V1aZPCQ1Y6kYmTkcjwNENs_Zz7gyxKOsfx0&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_APNeTBoxcHNxRtLdDDrPsvIfy3-2DI67C2ks5vckvOgaJpZM4WoRjQ&d=DwMCaQ&c=3_5eq9zYXWRS8ywqccmjfTRKM8mRLoQp6HBg1Tdb_Pc&r=nsJ1Vt4kkj1MF7fPuYx_OHpUcucCi7WPVJJQ5IIS6oA&m=C1-GFK88oKyYhu9ikTbOj7aLgY91vwhHUZO9-h-k_0g&s=7Mbwqn3pCzTxNKOWgHFDmd7fGGiTalAhDcT5_6zN3WM&e=>
> .
>


-- 
*Curt Mayer* | Senior Architect, Customer Success
Office 707.540.3441 | Mobile 707.540.3441
<http://appdynamics.com/>
Watch  <http://appdynamics.wistia.com/medias/56gnkuk6mv>our Video | Try
<https://portal.appdynamics.com/account/signup/signupForm>our FREE Trial |
Twitter  <http://www.twitter.com/appdynamics>| Facebook
<http://www.facebook.com/pages/AppDynamics/193264136815?ref=nf>|
appdynamics.com <http://www.appdynamics.com/>
