### ISSUE TITLE
No need for file difference map when fresh/empty secondary

### ISSUE THREAD

**Issue by rnav1234** [Appdynamics/HA-toolkit#98]
When a fresh/new/empty secondary is being added then there is no need to calculate the list of differences that need to be deleted from secondary. This step takes ~17mins for 2TB db/data

**Comment by cmayer68** [comment]
this is actually a general case.  the secondary files should be enumerated and sent back to the primary.  only these files need be checksum'ed, and this process should be done in parallel.
thus, the total pruning will speed up by at least half, and when doing an initial replicate, be immediate.

**Comment by rnav1234** [comment]
Resolved in release v3.50
